#ifndef _IOCTRL_H
#define _IOCTRL_H

#include "global.h"

#define KDRV_CTRL_SESSION CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0100, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

typedef struct _KDRV_SESSION_REQEUST
{
  PCHAR Command;
  ULONG Pid;
} KDRV_SESSION_REQEUST, * PKDRV_SESSION_REQEUST;

#endif